export const Category =[
  { value: "需求", count: 30 },
  { value: "设计", count: 29 },
  { value: "规格", count: 29 },
  { value: "技术", count: 27 },
  { value: "服务", count: 28 },
  { value: "管理", count: 26 },
  { value: "行政", count: 25 },
  { value: "其他", count: 27 },
]

export const Tags =[
  { value: "react", count: 60 },
  { value: "java", count: 50 },
  { value: "StartUML", count: 40 },
  { value: "Maven", count: 30 },
  { value: "Git", count: 35 },
  { value: "SVN", count: 44 },
  { value: "gitlab", count: 26 },
  { value: "ClearCase", count: 25 },
  { value: "ClearQuest", count: 25 },
  { value: "CHNGUIP", count: 25 },
  { value: "CHNBBOS", count: 25 },
  { value: "CHNEGSP", count: 25 },
  { value: "CHNCWAP", count: 25 },
  { value: "CHNEUIF", count: 25 },
  { value: "CHNODSS", count: 25 },
  { value: "CHNECIF", count: 25 },
  { value: "DEV1", count: 25 },
  { value: "DEV2", count: 25 },
  { value: "DEV3", count: 25 },
  { value: "DEV4", count: 25 },
  { value: "DEV5", count: 25 },
  { value: "DEV6", count: 25 },
]